name: Push to DockerHub
on:
  push:
    branches:
      - main
jobs:
  push:
    environment: common
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "Logging in to DockerHub"
      - shell: bash
        env:
          DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
        run: docker login -u xaionaro2 --password-stdin <<< "$DOCKERHUB_KEY"
      - run: echo "Building and pushing"
      - run: ${{ github.workspace }}/push-to-dockerhub.sh
