name: Force-push to registries
on:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  dockerhub:
    environment: dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ${{ github.workspace }}/push-to-registry.sh --force --only-latests
        env:
          REGISTRY_ADDR: registry.hub.docker.com
          REGISTRY_LOGIN: xaionaro2
          REGISTRY_KEY: ${{ secrets.REGISTRY_KEY }}
          REGISTRY_IMAGE_NAME: xaionaro2/edk2-builder
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ${{ github.workspace }}/push-to-registry.sh --force --only-latests
        env:
          REGISTRY_ADDR: ghcr.io
          REGISTRY_LOGIN: ${{ github.actor }}
          REGISTRY_KEY: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_IMAGE_NAME: ${{ github.repository }}

